export const LOGIN = 'login'
export const REGISTER = 'register'
export const URL = 'http://localhost:3000'

export const BUTTON = 'button'
export const CHECKBOX = 'checkbox'
export const CONFIRM_PASSWORD = 'confirm_password'
export const EMAIL = 'email'
export const LINK = 'link'
export const PASSWORD = 'password'
export const SELECT = 'select'
export const TEXT = 'text'
